version: '2'

services:
  mysql:
    dns:
      - 8.8.8.8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    image: 'mysql:5.6'

    tmpfs: /var/lib/mysql

  teamcity-agent:
    dns:
      - 8.8.8.8
    environment:
      - 'TEAMCITY_SERVER=http://ci.jetthoughts.com'

    build: .
  #  image: 'jetthoughts/teamcity-agent-docker:latest'

    links:
      - mysql
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/bin/docker'
      - '/mnt/storage/tmp/cache:/tmp/cache'
      - '/mnt/storage/tmp/opt/buildAgent:/opt/buildAgent'
networks:
  default:
    driver: bridge
