version: '2.1'

services:
  mysql:
    image: 'mysql:5.7'
    dns:
      - 8.8.8.8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    tmpfs:
      - /var/lib/mysql
    mem_limit: 1g
    restart: always

  agent:
    build: .
    dns:
      - 8.8.8.8
    links:
      - mysql
    environment:
      - TEAMCITY_SERVER=http://ci.jetthoughts.com
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - datavolume:/opt/buildAgent/
    restart: always

volumes:
  datavolume: {}
